### PR TITLE
scikit-learn-extra v0.3.0

### PR DESCRIPTION
**Pull request by stephenpardy**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by stephenpardy** [comment]
@conda-forge-admin, please rerender

**Comment by xhochy** [comment]
@conda-forge-admin please rerender

**Comment by xhochy** [comment]
@stephenpardy Add yourself as a maintainer here!

**Comment by stephenpardy** [comment]
> @stephenpardy Add yourself as a maintainer here!

Happy to do so. Is there a process for that beyond making a PR adding my name to the list?

**Comment by xhochy** [comment]
No, that's exactly it.

**Pull request merged**
